---
  - name: Create Web security group
    ec2_group:
      name: "{{ env }}-sg-web"
      region: "{{ region }}"
      description: allow web access from everywhere
      vpc_id: "{{ vpc_id }}"
      rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
    register: web_sec_group

  - name: Create Internal web security group
    ec2_group:
      name: "{{ env }}-vpc-web-internal"
      region: "{{ region }}"
      description: allow web access from internal network only
      vpc_id: "{{ vpc_id }}"
      rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: "{{ vpc_base }}.0.0/24"
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: "{{ vpc_base }}.1.0/24"

  - name: Create DB security group
    ec2_group:
      name: "{{ env }}-sg-db"
      region: "{{ region }}"
      description: allow access to db from web tier
      vpc_id: "{{ vpc_id }}"
      rules:
        - proto: tcp
          from_port: 3306
          to_port: 3306
          cidr_ip: "{{ vpc_base }}.0.0/24"
        - proto: tcp
          from_port: 3306
          to_port: 3306
          cidr_ip: "{{ vpc_base }}.1.0/24"
    register: db_sec_group

  - name: Create SSH security group
    ec2_group:
      name: "{{ env }}-vpc-ssh"
      region: "{{ region }}"
      description: allow ssh access
      vpc_id: "{{ vpc_id }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "{{control_ip}}"

  - name: Create outbound security group
    ec2_group:
      name: "{{ env }}-vpc-outbound"
      description: allow outbound connections to the internet
      region: "{{ region }}"
      vpc_id: "{{ vpc_id }}"
      rules_egress:
       - proto: all
         cidr_ip: 0.0.0.0/0
