---
  - name: Start the zone 1 server instances
    ec2:
      image: "{{ ubuntu_image.ami }}"
      region: "{{ region }}"
      instance_type: "{{ server.instance_type }}"
      assign_public_ip: True
      key_name: "{{ env }}_key"
      group: ["{{ env}}-vpc-web-internal", "{{ env}}-vpc-ssh", "{{ env}}-vpc-outbound"]
      instance_tags: { Name: "{{ env }}-z1-web", type: webserver, env: "{{ env }}", az: 1 }
      exact_count: "{{ server.zone_1_count }}"
      count_tag: { type: webserver, env: "{{ env }}", az: 1 }
      vpc_subnet_id: "{{ web_tier_subnet_1 }}"
      zone: "{{ zone_1 }}"
      wait: yes
    register: ec2

  - name: Wait for zone 1 servers to be reachable via SSH
    wait_for: host={{ item.public_dns_name }} port=22 search_regex=OpenSSH
    with_items: ec2.tagged_instances
    when: item.public_dns_name is defined

  - name: Start the zone 2 server instances
    ec2:
      image: "{{ ubuntu_image.ami }}"
      region: "{{ region }}"
      instance_type: "{{ server.instance_type }}"
      assign_public_ip: True
      key_name: "{{ env }}_key"
      group: ["{{ env}}-vpc-web-internal", "{{ env}}-vpc-ssh", "{{ env}}-vpc-outbound"]
      instance_tags: { Name: "{{ env }}-z2-web", type: webserver, env: "{{ env }}", az: 2 }
      exact_count: "{{ server.zone_2_count }}"
      count_tag: { type: webserver, env: "{{ env }}", az: 2 }
      vpc_subnet_id: "{{ web_tier_subnet_2 }}"
      zone: "{{ zone_2 }}"
      wait: yes
    register: ec2

  - name: Wait for zone 2 servers to be reachable via SSH
    wait_for: host={{ item.public_dns_name }} port=22 search_regex=OpenSSH
    with_items: ec2.tagged_instances
    when: item.public_dns_name is defined
