---
- name: Create the VPC
  ec2_vpc:
    region: "{{ region }}"
    internet_gateway: True
    resource_tags: { Name: "{{ env}}-vpc", env: "{{ env }}" }
    cidr_block: "{{ cidr_block }}"
    subnets: "{{ vpc.subnets }}"
    route_tables: "{{ vpc.route_tables }}"
  register: vpc

- set_fact: vpc_id="{{ vpc.vpc_id }}"
- set_fact: web_tier_subnet_1="{{ vpc.subnets[0].id}}"
- set_fact: web_tier_subnet_2="{{ vpc.subnets[1].id}}"
- set_fact: db_tier_subnet_1="{{ vpc.subnets[2].id}}"
- set_fact: db_tier_subnet_2="{{ vpc.subnets[3].id}}"

- name: Create key pair
  ec2_key: name="{{ env }}_key" region="{{ region }}"
  register: keypair

- name: Write the key to a file
  copy:
    dest: "keys/{{ env }}_key.pem"
    content: "{{ keypair.key.private_key }}"
    mode: 0600
  when: keypair.changed
