---
- name: Create RDS subnet
  rds_subnet_group:
    name: "{{ env }}-db-sng"
    region: "{{ region }}"
    state: present
    description: "RDS subnet group for {{ env }}"
    subnets:
      - "{{ db_tier_subnet_1 }}"
      - "{{ db_tier_subnet_2 }}"

- name: Create RDS database (this can take a while)
  rds:
    command: create
    instance_name: "{{ env }}-db"
    db_engine: MySQL
    size: "{{ db.size }}"
    instance_type: "{{ db.instance_type }}"
    multi_zone: yes
    username: "{{ db.user }}"
    password: "{{ db.password }}"
    tags: { Name: "{{ env }}-db", type: db, env: "{{ env }}" }
    subnet: "{{ env }}-db-sng"
    vpc_security_groups: ["{{ db_sec_group.group_id }}"]
    wait: yes
        wait_timeout: 1200
